### ISSUE TITLE
Where is the Big Title?

### ISSUE THREAD

**Issue by Hirbod** [zobeirhamid/react-native-scrollable-navigation-bar#10]
Hi, 

I am a user of your lib since day 1 and have updated today after couple of months and of course it broke everything. But the previews and the whole package looks AMAZING and this one here is by far the smoothest and best scroll/collapse react native scroll bar tool in the wild. Unfortunately, in all my tests, which went well so far, I couldn't get the big initial title @zobeirhamid.

What is wrong? The code is copied 1:1 form the example.

```js
                    <ScrollableNavigationBar
                        transitionPoint={250}
                        StatusBar={() => (
                            <StatusBarComponent
                                barStyle="dark-content"
                                backgroundColor="#f5f5f5"
                            />
                        )}
                        title="Title"
                        headerBackgroundColor="#f5f5f5"
                        borderColor="lightgrey"
                        BackButton={({ style }) => (
                            <BackButton
                                style={style}
                                onPress={() => NavigationService.goBack()}
                            />
                        )}
                        leftIcons={[<NavigationBarIcon name="ios-heart" />]}
                        rightIcons={[<NavigationBarIcon name="ios-rocket" />]}
                    >
```

See gif attached

![ezgif-5-1cd66beb8a71](https://user-images.githubusercontent.com/504909/68999243-50c33400-08be-11ea-838e-f9f1fd6bc6fe.gif)

**Comment by Hirbod** [comment]
Alright, this repo really needs a Readme.
Found out I need a HeaderForegroundComponent after inspecting HomeScreen.js

So not a bug!

**Comment by zobeirhamid** [comment]
You can also set the headerTitle prop to have a title component, sorry for the trouble I'm gonna write a big Readme in the next couple of weeks.

**Comment by Hirbod** [comment]
Oh wow... yeah. headerTitle was EXACTLY what I needed. LOL, because HeaderForeGround was nice, since I can do some interesting stuff with it, but not for now. AWESOME WORK @zobeirhamid
