### ISSUE TITLE
Error with SwitchNavigator StatusBarStack.length undefined

### ISSUE THREAD

**Issue by Hirbod** [zobeirhamid/react-native-scrollable-navigation-bar#12]
When I navigate (clicking the "logout button" in my app) using a switch navigator, I get this error

![IMG_7817](https://user-images.githubusercontent.com/504909/69001678-73b40f00-08e3-11ea-9cc2-e8dafa50ccfc.PNG)

**Comment by Hirbod** [comment]
PS: This error only happens if there is no 

```
                    StatusBar={() => (
                        <StatusBarComponent
                            barStyle="light-content"
                            backgroundColor="transparent"
                        />
                    )}
```

After I added this, the error is gone but force me to use the StatusBar (which is ok for me)

**Comment by zobeirhamid** [comment]
@Hirbod Thanks you for all your contributions, I really appreciate it! I'm gonna take a look at the PR tomorrow.
