### ISSUE TITLE
Add props to NavigationBarIcon

### ISSUE THREAD

**Issue by Hirbod** [zobeirhamid/react-native-scrollable-navigation-bar#17]
https://github.com/zobeirhamid/react-native-scrollable-navigation-bar/blob/master/src/components/NavigationBar/NavigationBarIcon.js#L16

So we could pass a hitSlop for example

**Comment by zobeirhamid** [comment]
@Hirbod First, I want to thank you for all your contributions, they are highly appreciated.
Next, I agree one should be able to pass Props to the Touchable Component, but I would rather prefer to be able to specify a TouchableComponent to have even greater control.

**Comment by Hirbod** [comment]
You're welcome. And yeah, that is a good idea!

**Comment by zobeirhamid** [comment]
Fixed.
