### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wahiche** [zobeirhamid/react-native-scrollable-navigation-bar#21]
First off this looks incredible and cannot wait to use it.

I know that you mentioned that the documentation is being worked on, and it does take a long time to do it, nobody likes doing documentation, but I am having trouble following the examples and it makes it seem like I need to create so many small pieces to get this to work.

If there any way that you could write even a very basic instruction on how to include this package into your app and use it with the simplest example?

It would also be nice to know all the props that the component accepts.

That would be awesome.

Thanks again for all your hard work.

**Comment by zobeirhamid** [comment]
Hello, sorry for the ultra late response, but I just finished writing the documentation.
https://zobeirhamid.github.io/react-native-scrollable-navigation-bar/
