### ISSUE TITLE
Question: Make Title Banner Smaller?

### ISSUE THREAD

**Issue by zaptrem** [zobeirhamid/react-native-scrollable-navigation-bar#5]
I want to make the large text banner slightly higher on the screen to match the Apple native version. What should be changed to achieve this? Thanks.

**Comment by zobeirhamid** [comment]
Hey.
You should be able to use the headerTitleStyle prop.

**Comment by zaptrem** [comment]
Thanks. Where should I put this prop and what are its potential values?

**Comment by zobeirhamid** [comment]
@zaptrem Just on the main component and it's a regular style prop, so fontSize.
