### ISSUE TITLE
App renders inproperly on Android only

### ISSUE THREAD

**Issue by Messi10AP** [zobeirhamid/react-native-scrollable-navigation-bar#7]
![IMG_3226](https://user-images.githubusercontent.com/11220954/66265276-d47b0280-e7e1-11e9-933c-2c3346dee242.PNG)
iOS

![IMG_0539-min](https://user-images.githubusercontent.com/11220954/66265279-dfce2e00-e7e1-11e9-89ce-d4ba9d26c551.png)
Android

**Comment by zobeirhamid** [comment]
@Messi10AP Thanks for the feedback. Try using the experimental branch, that is the updated branch.

**Comment by Messi10AP** [comment]
@zobeirhamid I also noticed that you used a custom version of react native in your examples. Is this necessary in order to use the library?

**Comment by Messi10AP** [comment]
Also, I tried to use the experimental branch, and it crashes with the error "Invariant Violation: Transform with key of translateY must be a number"

**Comment by zobeirhamid** [comment]
@Messi10AP Does the error occur on the example project? It uses a custom version which is not necessary, it was just to try some stuff out.

**Comment by Messi10AP** [comment]
No, it occured inside a project that I am currently using

**Comment by Messi10AP** [comment]
however, i just ran the example project and that seems to give an error as well

**Comment by zobeirhamid** [comment]
@Messi10AP Thanks for the feedback. I will take a look in the next days.

**Comment by zobeirhamid** [comment]
@Messi10AP It should work now.
